dist: trusty
sudo: require

language:
    - cpp
    - python

compiler:
    - gcc

python:
    - 3.4

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-7

script:
    - g++-7 --version
    - cd test
    - python3 test_all_solutions.py $TRAVIS_BUILD_DIR/solutions/ g++-7