dist: trusty
sudo: require

language: python

python:
    - 3.6

addons:
    apt:
        sources:
            - ubuntu-toolchain-r-test
        packages:
            - g++-5

script:
    - g++-5 --version && g++-5 -v # Check if proper version of g++ (>=5) is installed
    - python --version # Check if the proper version of python (>=3.6) is installed
    - cd tests # Enter test directory
    - python test_all_solutions.py $TRAVIS_BUILD_DIR g++-5 # Run all tests
